/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#imageHeaderPageSecondary[_ngcontent-%COMP%] {\n  background-image: url(../../../../assets/images/header.jpg);\n  background-size: 100% 100%;\n  height: 300px;\n}\n\n#titrePageSecondary[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvc2VjdGlvbnMvaGVhZGVyLXNlY29uZGFyeS9oZWFkZXItc2Vjb25kYXJ5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRGV2ZWxvcGVyL1BlcnNvL2Jyb2xpay1yZWNvcmRzL3NyYy9hcHAvY29tcG9uZW50cy9zZWN0aW9ucy9oZWFkZXItc2Vjb25kYXJ5L2hlYWRlci1zZWNvbmRhcnkuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
