/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['#imageHeaderPageSecondary[_ngcontent-%COMP%] {\n  background-image: url(../../../../assets/images/header.jpg);\n  background-size: 100% 100%;\n  height: 300px;\n}\n\n#titrePageSecondary[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}'];
//# sourceMappingURL=header-secondary.component.css.shim.ngstyle.js.map