/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['<<<<<<<[_ngcontent-%COMP%]   HEAD\n#headerIndex[_ngcontent-%COMP%] {\n  background-image: url(../../../../assets/images/logo.png);\n  background-size: 100% 100%;\n}\n\n.linkNews[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}\n\n#imgCash[_ngcontent-%COMP%] {\n  margin-left: 50px;\n  margin-top: 200px;\n  height: 300px;\n  width: 250px;\n  border-radius: 50px;\n  border: 10px grey solid;\n}\n\n#left[_ngcontent-%COMP%] {\n  float: left;\n}\n=======\n.linkNews[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}\n>>>>>>> f7f2c8009203bf2691585192a6c13289022a9566'];
//# sourceMappingURL=page-index.component.css.shim.ngstyle.js.map