/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['<<<<<<<[_ngcontent-%COMP%]   HEAD\n#headerIndex[_ngcontent-%COMP%] {\n  background-image: url(../../../../assets/images/logo.png);\n  background-size: 100% 100%;\n}\n\n.linkNews[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}\n\n#imgCash[_ngcontent-%COMP%] {\n  margin-left: 50px;\n  margin-top: 200px;\n  height: 300px;\n  width: 250px;\n  border-radius: 50px;\n  border: 10px grey solid;\n}\n\n#left[_ngcontent-%COMP%] {\n  float: left;\n}\n=======\n.linkNews[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}\n>>>>>>> f7f2c8009203bf2691585192a6c13289022a9566'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvcGFnZXMvcGFnZS1pbmRleC9wYWdlLWluZGV4LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRGV2ZWxvcGVyL1BlcnNvL2Jyb2xpay1yZWNvcmRzL3NyYy9hcHAvY29tcG9uZW50cy9wYWdlcy9wYWdlLWluZGV4L3BhZ2UtaW5kZXguY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
