/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.buttonReseauxSociaux[_ngcontent-%COMP%] {\n  cursor: pointer;\n  background-color: white;\n}\n#buttonFacebook[_ngcontent-%COMP%] {\n  margin-left: 10px;\n}\n.imageReseauxSociaux[_ngcontent-%COMP%] {\n  -webkit-transition: -webkit-transform 1s;\n  transition: transform 1s;\n}\n.imageReseauxSociaux[_ngcontent-%COMP%]:hover {\n  -ms-transform: rotate(360deg);\n  -webkit-transform: rotate(360deg);\n  transform: rotate(360deg);\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvc2VjdGlvbnMvcmVzZWF1eC1zb2NpYXV4L3Jlc2VhdXgtc29jaWF1eC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvc2VjdGlvbnMvcmVzZWF1eC1zb2NpYXV4L3Jlc2VhdXgtc29jaWF1eC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
