/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.buttonReseauxSociaux[_ngcontent-%COMP%] {\n  cursor: pointer;\n  background-color: white;\n}\n#buttonFacebook[_ngcontent-%COMP%] {\n  margin-left: 10px;\n}\n.imageReseauxSociaux[_ngcontent-%COMP%] {\n  -webkit-transition: -webkit-transform 1s;\n  transition: transform 1s;\n}\n.imageReseauxSociaux[_ngcontent-%COMP%]:hover {\n  -ms-transform: rotate(360deg);\n  -webkit-transform: rotate(360deg);\n  transform: rotate(360deg);\n}'];
//# sourceMappingURL=reseaux-sociaux.component.css.shim.ngstyle.js.map