/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#textAlignCenter[_ngcontent-%COMP%] {\n  text-align: center;\n}\n\n#itemsAlignCenter[_ngcontent-%COMP%] {\n  items-align: center;\n}\n\n#fullInputWidth[_ngcontent-%COMP%]{\n  width: 100%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvcGFnZXMvcGFnZS1uZXdzbGV0dGVyL3BhZ2UtbmV3c2xldHRlci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvcGFnZXMvcGFnZS1uZXdzbGV0dGVyL3BhZ2UtbmV3c2xldHRlci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
