/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#footer[_ngcontent-%COMP%] {\n  background-color: white;\n}\n\n.fullSize[_ngcontent-%COMP%] {\n  width: 100%;\n  height: 100%;\n}\n\n.linkReseauxSociaux[_ngcontent-%COMP%] {\n  color: #8BC34A;\n}\n\n#buttonBrolikRecords[_ngcontent-%COMP%] {\n  cursor: pointer;\n  background-color: white;\n  margin-right: 120px;\n}\n\n.gridPageSecondaire[_ngcontent-%COMP%] {\n  width: 70%;\n}\n\n.fontWhite[_ngcontent-%COMP%] {\n  color: white;\n}\n\n.fullWidth[_ngcontent-%COMP%] {\n  width: 100%;\n}\n\n.fontCenter[_ngcontent-%COMP%] {\n  text-align: center;\n}\n\n.itemCenter[_ngcontent-%COMP%] {\n  items-align: center;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
