/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../src/app/components/sections/welcome/welcome.component';
const styles_WelcomeComponent:any[] = ([] as any[]);
export const RenderType_WelcomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_WelcomeComponent,data:{}});
export function View_WelcomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    var _co:i1.WelcomeComponent = _v.component;
    const currVal_0:any = _co.message;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_WelcomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-welcome',
      ([] as any[]),(null as any),(null as any),(null as any),View_WelcomeComponent_0,
      RenderType_WelcomeComponent)),i0.ɵdid(49152,(null as any),0,i1.WelcomeComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const WelcomeComponentNgFactory:i0.ComponentFactory<i1.WelcomeComponent> = i0.ɵccf('app-welcome',
    i1.WelcomeComponent,View_WelcomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvc2VjdGlvbnMvd2VsY29tZS93ZWxjb21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EZXZlbG9wZXIvUGVyc28vYnJvbGlrLXJlY29yZHMvc3JjL2FwcC9jb21wb25lbnRzL3NlY3Rpb25zL3dlbGNvbWUvd2VsY29tZS5jb21wb25lbnQudHMiLCJuZzovLy9EZXZlbG9wZXIvUGVyc28vYnJvbGlrLXJlY29yZHMvc3JjL2FwcC9jb21wb25lbnRzL3NlY3Rpb25zL3dlbGNvbWUvd2VsY29tZS5jb21wb25lbnQudHMuV2VsY29tZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vRGV2ZWxvcGVyL1BlcnNvL2Jyb2xpay1yZWNvcmRzL3NyYy9hcHAvY29tcG9uZW50cy9zZWN0aW9ucy93ZWxjb21lL3dlbGNvbWUuY29tcG9uZW50LnRzLldlbGNvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJ7e21lc3NhZ2V9fSIsIjxhcHAtd2VsY29tZT48L2FwcC13ZWxjb21lPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBOztJQUFBO0lBQUE7Ozs7b0JDQUE7TUFBQTtpQ0FBQSxVQUFBO01BQUE7OzsifQ==
