/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['#textAlignCenterBis[_ngcontent-%COMP%] {\n  text-align: center;\n}\n\n#itemsAlignCenterBis[_ngcontent-%COMP%] {\n  items-align: center;\n}\n\n.fullWidthBis[_ngcontent-%COMP%] {\n  width: 100%;\n}'];
//# sourceMappingURL=page-contact.component.css.shim.ngstyle.js.map