/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.hauteurVideoMusique[_ngcontent-%COMP%] {\n  height: 500px;\n}\n\n.frameVideo[_ngcontent-%COMP%] {\n  width: 100%;\n  height: 90%;\n}'];
//# sourceMappingURL=page-videos.component.css.shim.ngstyle.js.map