/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.hauteurVideoMusique[_ngcontent-%COMP%] {\n  height: 500px;\n}\n\n.frameVideo[_ngcontent-%COMP%] {\n  width: 100%;\n  height: 90%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0RldmVsb3Blci9QZXJzby9icm9saWstcmVjb3Jkcy9zcmMvYXBwL2NvbXBvbmVudHMvcGFnZXMvcGFnZS12aWRlb3MvcGFnZS12aWRlb3MuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EZXZlbG9wZXIvUGVyc28vYnJvbGlrLXJlY29yZHMvc3JjL2FwcC9jb21wb25lbnRzL3BhZ2VzL3BhZ2UtdmlkZW9zL3BhZ2UtdmlkZW9zLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
